---
- name: Install and configure Apache
  hosts: tag_acs730
  become: yes
  gather_facts: true
  vars:
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3.8
    image_source: ./demo.png
    image_dest: /var/www/html/demo.png
    source_file: ./index.html
    dest_file: /var/www/html/index.html

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
        use_backend: dnf4

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Wait for Apache to start
      wait_for:
        port: 80
        state: started
        delay: 5
        timeout: 30
    
    - name: Deploy index.html
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
        mode: '0644'
      notify: Restart Httpd
      
    - name: Deploy demo image
      copy:
        src: "{{ image_source }}"
        dest: "{{ image_dest }}"
        mode: '0644'
      notify: Restart Httpd

  handlers:
    - name: Restart Httpd
      service:
        name: httpd
        state: restarted
